#ifndef HELERIS_ERROR_CODES_H
#define HELERIS_ERROR_CODES_H

enum EHRSErrorCodes {
    // Memory management errors
    HRS_ERROR_MALLOC_ERROR = 1,
    HRS_ERROR_REALLOC_ERROR,
    HRS_ERROR_FREE_ERROR,
    HRS_ERROR_TRY_TO_USE_NULL,
    // General errors
    HRS_ERROR_FAILED_INITIALIZE,
    HRS_ERROR_INCOMPATIBILITY,
    HRS_ERROR_INCOMPATIBLE_STATUS,
    HRS_ERROR_INCOMPATIBLE_ARGUMENT,
    // GLFW errors
    HRS_ERROR_GLFW_CANT_INIT,
    HRS_ERROR_GLFW_CANT_MAKE_WINDOW,
    // GLAD errors
    HRS_ERROR_GLAD_CANT_FIND_IMPLEMENTATIONS,
    // HRSGLContext errors
    HRS_ERROR_HRSGLC_ALREADY_INITIALIZED,
    HRS_ERROR_HRSGLC_NOT_INITIALIZED,
    // HRSContextLoader erros
    HRS_ERROR_HRSCLD_LOAD_FAILED,
    // Shader errors
    HRS_ERROR_SHADER_FAILED_COMPILATION,
};

#endif 